import webbrowser
import cgi
import wsgiref
import uuid
import urllib
import urllib2
import urlparse
import httplib
import ftplib
import poplib
import imaplib
import smtplib
import telnetlib
import cookielib
import Cookie
import xmlrpclib
import SocketServer
import BaseHTTPServer
import SimpleHTTPServer
import CGIHTTPServer
import SimpleXMLRPCServer
import DocXMLRPCServer
