application: ksvshack
version: 1
runtime: python
api_version: 1
threadsafe: false

handlers:

- url: /_ah/mail/.+
  script: handle_incoming_email.py
  login: admin

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: .*
  script: main.py

inbound_services:
- mail
