;;; This file was automatically generated by the panel editor.
;;; If you read it into gnu emacs, it will automagically format itself.

(panel (prop help creator:user-panel-help)
(prop user-panel #t)
(label "frames per second")
(al (pnl_toggle_button (name "freeze")
(prop help creator:user-act-help)
(label "freeze")
(x 0.25)
(y 4.3)
(w 1.45)
(h 0.6)
(labeltype 16)
(downfunc move-then-resize)
)
(pnl_scale_chart (name "mystrip")
(prop help creator:user-act-help)
(x 0.25)
(y 0.25)
(downfunc move-then-resize)
)
)
)
;;; Local Variables:
;;; mode: scheme
;;; eval: (save-excursion (goto-char (point-min)) (kill-line 3))
;;; eval: (save-excursion (goto-char (point-min)) (replace-regexp "[ \n]*)" ")"))
;;; eval: (indent-region (point-min) (point-max) nil)
;;; eval: (progn (kill-line -3) (delete-backward-char 1) (save-buffer))
;;; End:
