#!/usr/bin/python
"""
$Id$

Purpose:
    Purpose of this program. This can be a free format text and explains why I
    initially wrote this program.

Description:
    Description of the solution. Sometimes the description can be null. The
    script should take both the  purpose and description, format it properly
    and display.

Source:
    If the source of the program is elsewhere, credit it here.

"""
import this
def test1():
    """This is a comment"""
    x = 0
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))

    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))

    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))

    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))

    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))

    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))

    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))

    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))

    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))

    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))

    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))

    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))

    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))

    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))

    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))

    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))

    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))

    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))

    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))

    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))

    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))

    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))

    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))

    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))

    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))

    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))

    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))

    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))

    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))

    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))
    if x: x = (x + x + (x + x) + (x + x + (x + x))) + (x + x + (x + x) + (x + x + (x + x)))

print len(test1.func_code.co_code)

class Collect(object):
    def __init__(self):
        self.items = []
    def write(self, value):
        self.items.append(value)

import sys, dis

_, dis_output = old_stdout, sys.stdout = sys.stdout, Collect()

dis.dis(test1)

dis_output = ''.join(dis_output.items).splitlines()

sys.stdout = old_stdout

print '\n'.join(dis_output[:20])
