# -*- coding: utf-8 -*-
#
# uthcode documentation build configuration file, created by
# sphinx-quickstart on Sat Oct 24 18:08:47 2009.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

from datetime import date

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
# source_encoding = 'utf-8-sig'

master_doc = 'index'

# General information about the project.
project = u'Learn To Solve It'
copyright = f'{date.today().year} Senthil Kumaran'

version = '2022-01-06'
# The full version, including alpha/beta/rc tags.
release = ''

today_fmt = '%d %b of %y'

# List of documents that shouldn't be included in the build.
unused_docs = []

# List of directories, relative to source directory, that shouldn't be searched
# for source files.
exclude_trees = []

pygments_style = 'friendly'

html_title = 'Learn To Solve It'

# A shorter title for the navigation bar.  Default is the same as html_title.
html_short_title = 'Learn To Solve It'

html_static_path = ['_static']

html_extra_path = ["Ads.txt"]

# These paths are either relative to html_static_path
# or fully qualified paths (eg. https://...)

html_css_files = [
    'css/custom.css',
]

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
html_last_updated_fmt = '%d %b, %y'
html_sidebars = {'**': ['logo.html', 'globaltoc.html']}

# If false, no module index is generated.
html_use_modindex = False

# If false, no index is generated.
html_use_index = False

# If true, links to the reST sources are added to the pages.
html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
html_show_sphinx = False

# Output file base name for HTML help builder.
htmlhelp_basename = 'uthcodedoc'

try:
    extensions
except NameError:
    extensions = []

extensions.append('sphinx_wagtail_theme')
html_theme = 'sphinx_wagtail_theme'

project = ""
# These are options specifically for the Wagtail Theme.
html_theme_options = dict(
    project_name ="Learn To Solve It",
    logo = "uthcode-logo-transparent.png",
    logo_alt = "",
    github_url = "https://github.com/uthcode/learntosolveit/blob/master/source/",
    logo_height = 59,
    logo_url = "/",
    logo_width = 45,
    header_links = "Computer Science Courses|https://courses.learntosolveit.com/, Anki| https://ankiweb.net/decks, Projects|https://projects.learntosolveit.com/, Just Do Beaver|https://www.justdobeaver.com/",
    footer_links = ",".join([
        "Senthil Kumaran|https://senthil.learntosolveit.com/",
    ]),
)